import type {
  AlphaCandidate,
  EntityCluster,
  Holding,
  IntelligenceAlert,
  MacroIndicator,
  MorningBrief,
  PortfolioSignal,
  PortfolioSummary,
  WalletIntelligence,
  WatchlistItem,
  WatchRule,
} from "@/lib/types";

export const holdings: Holding[] = [
  {
    id: "holding-btc",
    assetId: "bitcoin",
    symbol: "BTC",
    name: "Bitcoin",
    quantity: 0.42,
    averageBuyPrice: 62800,
    currentPrice: 68740,
    change24h: 1.7,
    notes: "Core long-term position",
  },
  {
    id: "holding-eth",
    assetId: "ethereum",
    symbol: "ETH",
    name: "Ethereum",
    quantity: 5.8,
    averageBuyPrice: 2850,
    currentPrice: 4120,
    change24h: -0.8,
  },
  {
    id: "holding-sol",
    assetId: "solana",
    symbol: "SOL",
    name: "Solana",
    quantity: 82,
    averageBuyPrice: 181,
    currentPrice: 132,
    change24h: -4.9,
    notes: "Review after ecosystem updates",
  },
  {
    id: "holding-arb",
    assetId: "arbitrum",
    symbol: "ARB",
    name: "Arbitrum",
    quantity: 4200,
    averageBuyPrice: 1.32,
    currentPrice: 0.84,
    change24h: -6.4,
  },
];

export const portfolioSummary: PortfolioSummary = {
  totalValue: 67271.4,
  totalInvested: 64830,
  unrealizedPl: 2441.4,
  unrealizedPlPercent: 3.77,
  change24h: -1.42,
  topGainer: "BTC",
  topLoser: "ARB",
  macroStatus: "NEUTRAL",
  fearGreed: {
    value: 38,
    label: "Fear",
  },
};

export const portfolioSignals: PortfolioSignal[] = [
  {
    assetId: "bitcoin",
    signal: "HOLD",
    confidence: "MEDIUM",
    reason: "BTC is trading within the configured hold band relative to your average buy price.",
  },
  {
    assetId: "ethereum",
    signal: "TAKE_PROFIT",
    confidence: "HIGH",
    reason: "ETH is 44.6% above your average buy price. This is within the take-profit review zone.",
  },
  {
    assetId: "solana",
    signal: "BUY_ZONE",
    confidence: "MEDIUM",
    reason: "SOL is more than 20% below your average buy price while macro risk is not currently risk-off.",
  },
  {
    assetId: "arbitrum",
    signal: "RISK_WARNING",
    confidence: "HIGH",
    reason: "ARB is down more than 30% from your average buy price and sentiment remains in Fear territory.",
  },
];

export const alphaCandidates: AlphaCandidate[] = [
  {
    assetId: "celestia",
    rank: 1,
    symbol: "TIA",
    name: "Celestia",
    priceUsd: 12.84,
    marketCap: 2360000000,
    volume24h: 198000000,
    priceChange24h: 8.4,
    priceChange7d: 21.7,
    volumeToMarketCap: 8.4,
    alphaScore: 86,
    riskLevel: "MEDIUM",
    rationale: "Unusual volume acceleration and strong 7d momentum make this worth manual review.",
    watched: true,
  },
  {
    assetId: "render-token",
    rank: 2,
    symbol: "RNDR",
    name: "Render",
    priceUsd: 9.16,
    marketCap: 3520000000,
    volume24h: 246000000,
    priceChange24h: 4.1,
    priceChange7d: 16.2,
    volumeToMarketCap: 7.0,
    alphaScore: 78,
    riskLevel: "MEDIUM",
    rationale: "Narrative relevance and liquidity remain constructive, with moderate volatility.",
    watched: false,
  },
  {
    assetId: "ondo-finance",
    rank: 3,
    symbol: "ONDO",
    name: "Ondo",
    priceUsd: 1.42,
    marketCap: 1980000000,
    volume24h: 164000000,
    priceChange24h: 2.8,
    priceChange7d: 12.1,
    volumeToMarketCap: 8.3,
    alphaScore: 73,
    riskLevel: "LOW",
    rationale: "Steady momentum and strong liquidity proxy place it in the watchlist candidate range.",
    watched: false,
  },
  {
    assetId: "akash-network",
    rank: 4,
    symbol: "AKT",
    name: "Akash Network",
    priceUsd: 4.91,
    marketCap: 1190000000,
    volume24h: 48000000,
    priceChange24h: 14.9,
    priceChange7d: 28.4,
    volumeToMarketCap: 4.0,
    alphaScore: 71,
    riskLevel: "HIGH",
    rationale: "Momentum is strong, but volatility requires a higher-risk manual review.",
    watched: false,
  },
];

export const watchlist: WatchlistItem[] = [
  {
    id: "watch-tia",
    symbol: "TIA",
    name: "Celestia",
    alphaScore: 86,
    currentPrice: 12.84,
    rationale: "Volume acceleration and 7d momentum are above the MVP watch threshold.",
    notes: "Review ecosystem catalysts.",
  },
  {
    id: "watch-ondo",
    symbol: "ONDO",
    name: "Ondo",
    alphaScore: 73,
    currentPrice: 1.42,
    rationale: "Liquidity and narrative relevance remain constructive.",
  },
];

export const macroIndicators: MacroIndicator[] = [
  {
    id: "fed-funds",
    name: "Fed Funds Rate",
    value: "5.25%",
    trend: "FLAT",
    interpretation: "Rate pressure is not improving yet, but it is not accelerating.",
  },
  {
    id: "cpi-yoy",
    name: "CPI YoY",
    value: "3.1%",
    trend: "DOWN",
    interpretation: "Cooling inflation is supportive for risk assets.",
  },
  {
    id: "ten-year",
    name: "10Y Treasury Yield",
    value: "4.42%",
    trend: "UP",
    interpretation: "Yield pressure remains a headwind for speculative assets.",
  },
  {
    id: "m2",
    name: "M2 Money Supply",
    value: "$20.9T",
    trend: "UP",
    interpretation: "Liquidity trend is modestly constructive.",
  },
];

export const morningBrief: MorningBrief = {
  title: "Morning Brief",
  date: "2026-05-29",
  marketStatus: "NEUTRAL",
  macroStatus: "NEUTRAL",
  generatedAt: "2026-05-29 07:12",
  sourceFreshness: "Market data refreshed 12 minutes ago. Macro data refreshed today.",
  sections: [
    {
      title: "Market overview",
      body: "Crypto market conditions are neutral to cautious. BTC is holding above its average cost basis while ETH remains the strongest contributor in the portfolio.",
    },
    {
      title: "Macro condition",
      body: "Macro status is Neutral. Cooling CPI and improving liquidity are offset by elevated 10Y yield pressure.",
    },
    {
      title: "Portfolio movement",
      body: "The portfolio is down 1.42% over 24h, mainly affected by SOL and ARB weakness.",
    },
    {
      title: "Assets to review",
      body: "ETH is in a take-profit review zone. ARB has a risk warning due to drawdown and weak sentiment.",
    },
    {
      title: "Alpha hunter candidates",
      body: "TIA, RNDR, and ONDO show unusual activity based on public market data and may be worth manual review.",
    },
  ],
};

export const walletIntelligence: WalletIntelligence[] = [
  {
    address: "bc1q9f2n8x7d3m5w4v6r2s0k8l4p6a3t9c2e5z7h1m",
    chain: "BITCOIN",
    addressType: "Native SegWit",
    entityId: "entity-btc-whale-cluster",
    entityName: "BTC Accumulation Cluster",
    firstSeenAt: "2022-11-18",
    lastSeenAt: "2026-05-29",
    balanceUsd: 18462000,
    netFlow24hUsd: 1280000,
    activityScore: 82,
    smartFlowScore: 76,
    exchangePressure: "OUTFLOW",
    labels: [
      {
        label: "High-balance BTC cluster",
        category: "WHALE",
        confidence: "MEDIUM",
        sourceType: "HEURISTIC",
        sourceRef: "common-input and consolidation heuristics",
        explanation: "Clustered from repeated co-spends and long-horizon accumulation behavior. This is not a verified identity.",
      },
      {
        label: "Self-custody pattern",
        category: "UNKNOWN",
        confidence: "LOW",
        sourceType: "HEURISTIC",
        sourceRef: "UTXO age and exchange outflow pattern",
        explanation: "Recent exchange-like outflows are followed by low-churn UTXO holding behavior.",
      },
    ],
    events: [
      {
        id: "btc-event-1",
        chain: "BITCOIN",
        type: "UTXO_RECEIVE",
        asset: "BTC",
        amount: 12.4,
        valueUsd: 852376,
        counterparty: "Exchange-like hot wallet cluster",
        timestamp: "2026-05-29 06:42",
        txHash: "f2a67c9e8d4b7a3c1e2f90184b6c5d0a2f4e7b9c8d1a3e6f9b2c4d8a0e1f7b6c",
      },
      {
        id: "btc-event-2",
        chain: "BITCOIN",
        type: "UTXO_SPEND",
        asset: "BTC",
        amount: 2.1,
        valueUsd: 144354,
        counterparty: "Fresh change cluster",
        timestamp: "2026-05-28 19:15",
        txHash: "a6d3b8c2e1f94a0d7c6b5e4f3a2d1c0b9e8f7a6d5c4b3e2f1a0d9c8b7e6f5a4",
      },
    ],
    bitcoinUtxos: [
      { txid: "f2a67c9e8d4b7a3c1e2f90184b6c5d0a2f4e7b9c8d1a3e6f9b2c4d8a0e1f7b6c", vout: 0, valueSats: 1240000000, ageDays: 0, status: "UNSPENT" },
      { txid: "c7e2f8a9b4d1c0e6f5a3b2c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9", vout: 2, valueSats: 820000000, ageDays: 183, status: "UNSPENT" },
      { txid: "b1d4f7a0c3e6b9d2f5a8c1e4b7d0f3a6c9e2b5d8f1a4c7e0b3d6f9a2c5e8b1d4", vout: 1, valueSats: 210000000, ageDays: 4, status: "SPENT" },
    ],
  },
  {
    address: "7aVw9xZsM2pQ8rYh6Lc3Tn4Dg1Bf5Ke9Uj2Ns8PqR4Lm",
    chain: "SOLANA",
    addressType: "System account",
    entityId: "entity-sol-defi-operator",
    entityName: "Solana DeFi Operator",
    firstSeenAt: "2024-02-04",
    lastSeenAt: "2026-05-29",
    balanceUsd: 3421000,
    netFlow24hUsd: -420000,
    activityScore: 91,
    smartFlowScore: 84,
    exchangePressure: "NEUTRAL",
    labels: [
      {
        label: "Active DeFi operator",
        category: "WHALE",
        confidence: "MEDIUM",
        sourceType: "HEURISTIC",
        sourceRef: "DEX interaction and token routing pattern",
        explanation: "Repeated high-value swaps and liquidity routing across known Solana programs.",
      },
      {
        label: "User-reviewed watch wallet",
        category: "USER",
        confidence: "HIGH",
        sourceType: "USER_SUBMITTED",
        sourceRef: "workspace watchlist",
        explanation: "Manually added by the workspace user for monitoring.",
      },
    ],
    events: [
      {
        id: "sol-event-1",
        chain: "SOLANA",
        type: "SWAP",
        asset: "SOL",
        amount: 3180,
        valueUsd: 419760,
        counterparty: "Jupiter route",
        timestamp: "2026-05-29 05:18",
        txHash: "5mZ8wL4qP2rS9xN6tV3cB7kY1hD4aF8jQ6pE2nR9sT5u",
      },
      {
        id: "sol-event-2",
        chain: "SOLANA",
        type: "PROGRAM_CALL",
        asset: "USDC",
        amount: 250000,
        valueUsd: 250000,
        counterparty: "Lending market",
        timestamp: "2026-05-28 22:03",
        txHash: "2qK9nD5sP8vX3mL7cR1tY6aF4hJ0bN2wE5uS9zG8pA6d",
      },
    ],
    solanaPrograms: [
      {
        program: "Jupiter Aggregator",
        interactions24h: 9,
        interpretation: "High routing activity suggests active repositioning rather than passive holding.",
      },
      {
        program: "Token Program",
        interactions24h: 24,
        interpretation: "Frequent SPL token movement across associated token accounts.",
      },
    ],
  },
];

export const entityClusters: EntityCluster[] = [
  {
    id: "entity-btc-whale-cluster",
    name: "BTC Accumulation Cluster",
    category: "WHALE",
    chains: ["BITCOIN"],
    confidence: "MEDIUM",
    walletCount: 18,
    balanceUsd: 74200000,
    netFlow24hUsd: 4820000,
    rationale: "Common-input ownership and repeated exchange-outflow consolidation suggest one high-balance cluster, but ownership is probabilistic.",
    wallets: [
      { address: "bc1q9f2n8x7d3m5w4v6r2s0k8l4p6a3t9c2e5z7h1m", chain: "BITCOIN", confidence: "MEDIUM" },
      { address: "bc1q73k0n5v8d2m9x4p6q1r7s3t5a8c0e2h9j4l6n", chain: "BITCOIN", confidence: "LOW" },
    ],
  },
  {
    id: "entity-sol-defi-operator",
    name: "Solana DeFi Operator",
    category: "WHALE",
    chains: ["SOLANA"],
    confidence: "MEDIUM",
    walletCount: 6,
    balanceUsd: 9650000,
    netFlow24hUsd: -760000,
    rationale: "Shared funding source and repeated routing behavior across Solana DeFi programs indicate likely operational linkage.",
    wallets: [
      { address: "7aVw9xZsM2pQ8rYh6Lc3Tn4Dg1Bf5Ke9Uj2Ns8PqR4Lm", chain: "SOLANA", confidence: "MEDIUM" },
      { address: "3rPq8LmN6sT2uV9xY4aB7cD1eF5gH8jK0mN2pQ6rS9tU", chain: "SOLANA", confidence: "LOW" },
    ],
  },
];

export const watchRules: WatchRule[] = [
  {
    id: "rule-btc-whale-inflow",
    name: "BTC whale exchange outflow",
    chain: "BITCOIN",
    target: "BTC Accumulation Cluster",
    condition: "Alert when 24h net outflow from exchange-like clusters exceeds $1M.",
    status: "ACTIVE",
  },
  {
    id: "rule-sol-defi-rotation",
    name: "SOL DeFi rotation",
    chain: "SOLANA",
    target: "Solana DeFi Operator",
    condition: "Alert when watched wallet swaps more than $250k in 24h.",
    status: "ACTIVE",
  },
];

export const intelligenceAlerts: IntelligenceAlert[] = [
  {
    id: "alert-btc-1",
    severity: "HIGH",
    chain: "BITCOIN",
    title: "Large BTC exchange outflow detected",
    detail: "Watched BTC cluster received 12.4 BTC from an exchange-like hot wallet cluster. Review accumulation context.",
    timestamp: "2026-05-29 06:42",
    target: "BTC Accumulation Cluster",
  },
  {
    id: "alert-sol-1",
    severity: "MEDIUM",
    chain: "SOLANA",
    title: "Solana DeFi wallet repositioned",
    detail: "Watched wallet routed high-value SOL swaps through Jupiter. This is observed activity, not a trade instruction.",
    timestamp: "2026-05-29 05:18",
    target: "Solana DeFi Operator",
  },
];
